"""Add phone number to users table

Revision ID: 734e67aa3cde
Revises: 3b668b9aa1db
Create Date: 2021-12-19 15:30:43.616343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734e67aa3cde'
down_revision = '3b668b9aa1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
